#defaultView:Dimensions

SELECT ?memberLabel ?othersLabel


WHERE {

   	?member	wdt:P463 wd:Q5275956 .

    ?member	wdt:P463 ?others .

            

  SERVICE wikibase:label {

		bd:serviceParam wikibase:language "en" .

    

}

  }
