SELECT DISTINCT ?item ?itemLabel ?seLabel ?sym  WHERE {

  ?item wdt:P414 ?se;

        p:P414 [pq:P249 ?sym].

  ?item (wdt:P31/wdt:P279*) wd:Q4830453.

  {?item wdt:P452 wd:Q880371}

  UNION {?item wdt:P1056 wd:Q7397}.

  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }

}
