SELECT DISTINCT ?software ?softwareLabel ?licenseLabel ?image WHERE {

  ?software wdt:P1072 wd:Q178051.

  OPTIONAL { ?software wdt:P275 ?license. }

  OPTIONAL { ?software wdt:P154 ?image. }

  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }

}
