SELECT DISTINCT ?software ?softwareLabel ?userManualLink ?logo


WHERE {

  ?software wdt:P31/wdt:P279* wd:Q7397 .

   ?software wdt:P366 wd:Q336.

   ?software wdt:P2078 ?userManualLink.

  OPTIONAL {?software wdt:P154 ?logo}.      

  SERVICE wikibase:label {

		bd:serviceParam wikibase:language "en" .

    

}

  }
