SELECT DISTINCT ?software ?softwareLabel ?locNAFid ?logo

WHERE 

{

  ?software wdt:P31/wdt:P279* wd:Q7397.

  ?software wdt:P244 ?locNAFid.

  OPTIONAL {?software wdt:P154 ?logo}.

  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }

}
