#defaultView:ImageGrid

SELECT DISTINCT ?comp ?compLabel ?archiveidLabel ?image WHERE {

  ?comp (wdt:P31/wdt:P279*) wd:Q8076.

  ?comp wdt:P724 ?archiveid.

  OPTIONAL { ?comp wdt:P18 ?image. }

  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }

}
