SELECT ?signature ?codingLabel WHERE {
  wd:Q1238229 p:P4152 ?signatureStmt.
  ?signatureStmt ps:P4152 ?signature.
  ?signatureStmt pq:P3294 ?coding.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE], en". }
}
