#defaultView:ImageGrid

SELECT  ?personLabel  ?image 


WHERE {

  ?person wdt:P166 wd:Q1389573 .

  ?person wdt:P18 ?image .

  SERVICE wikibase:label {

		bd:serviceParam wikibase:language "en" .

    

}

  }
