SELECT ?emulator ?emulatorLabel ?image

WHERE {

  

  ?emulator wdt:P31 wd:Q202871 .

  ?emulator wdt:P154 ?image .          

  SERVICE wikibase:label {

		bd:serviceParam wikibase:language "en" .

    

}

  }
